### ISSUE TITLE
direct implementation of silex app in bootstrap.php ?

### ISSUE THREAD

**Issue by pitpit** [creads/silex-starter#1]
Why don't you use direct implementation of silex app in your bootstrap file ? It shared Application init code and I find it more concise :

web/index.php:
```
<?php

$app = require __DIR__.'/../app/app.php';
$app->run();
```

app/bootstrap.php:
```
<?php
require_once __DIR__.'/../vendor/autoload.php';
$app = new Silex\Application();

//...

return $app;
```

app/console.php:
```
<?php
$app = require __DIR__.'/../app/app.php';
$app['console']->run();
```

**Comment by qpautrat** [comment]
Because i want to set as a global parameter the application environment based on which bootstrap file is called.

**Comment by pitpit** [comment]
the bootstrap file must be the same on each environment. There is not reason to duplicate it.
Related  env parameters must stand in a config file.

**Comment by pitpit** [comment]
if you need to detect the current env, set a global var  in index_dev.php like:

    putenv('APP_ENV=dev');

and detect it in bootstrap.php:

  $app['env'] = getenv('APP_ENV') ?: 'dev';
