### ISSUE TITLE
Set debug application parameter

### ISSUE THREAD

**Issue by qpautrat** [creads/silex-starter#2]
In bootstrap, we forgot to set global `debug` parameter.
Use config loaded by `Igorw\Silex\ConfigServiceProvider`

**Comment by pitpit** [comment]
here's a snippet to put in app to load a global config and a dedicated  config override for current environment :

* app/config/config.yml
* app/config/config_dev.yml
* app/config/config_prod.yml 

```
$app->register(new Igorw\Silex\ConfigServiceProvider(__DIR__.'/config/config.yml'));
if (file_exists(__DIR__."/config/config_{$app['env']}.yml")) {
    $app->register(new Igorw\Silex\ConfigServiceProvider(__DIR__."/config/config_{$app['env']}.yml"));
}
```

Environment config files are not required (and can be excluded). There's no need for parameters anymore.
