### ISSUE TITLE
When using index_dev.php with internal php server, existent files must be served as it :

### ISSUE THREAD

**Issue by pitpit** [creads/silex-starter#3]
Use the following snippet to exclude files :

```
$filename = __DIR__.preg_replace('#(\?.*)$#', '', $_SERVER['REQUEST_URI']);
if (php_sapi_name() === 'cli-server' && is_file($filename)) {
    return false;
}
```

**Comment by qpautrat** [comment]
I don't understand what you saying.
Can you give me a use case please ?

**Comment by pitpit** [comment]
you need to run the internal server for DEV env :

    php -S localhost:8080 -t web web/index_dev.php

and try to access an asset file you created in web/ directory (ie: a jpg file).

The file won't be reachable if you don't prevent index_dev.php to catch the request
